-- =============================================
-- Script creazione tabelle vehicles_db
-- =============================================

CREATE TABLE vehicle_types (
  id_vehicle_type INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_type_name varchar NOT NULL
);

CREATE TABLE vehicle_alimentation_types (
  id_vehicle_alimentation_type INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_alimentation_type_name varchar NOT NULL
);

CREATE TABLE vehicle_brands (
  id_vehicle_brand INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_brand_name varchar NOT NULL
);

CREATE TABLE vehicle_models (
  id_vehicle_model INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_model_name varchar NOT NULL,
  id_vehicle_brand integer NOT NULL
);

CREATE TABLE vehicle (
  id_vehicle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle_type integer NOT NULL,
  id_vehicle_model integer NOT NULL,
  id_vehicle_alimentation_type integer NOT NULL,
  id_vehicle_brand integer NOT NULL,
  color varchar NOT NULL,
  number_of_wheels integer NOT NULL,
  numbers_of_gears integer NOT NULL,
  production_year date NOT NULL
);

CREATE TABLE cars (
  id_car INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle integer NOT NULL,
  licence_plate varchar NOT NULL,
  cc integer,
  number_of_doors integer NOT NULL
);

CREATE TABLE motorbikes (
  id_motorbike INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle integer NOT NULL,
  licence_plate varchar NOT NULL,
  cc integer
);

CREATE TABLE bikes (
  id_bike INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle integer NOT NULL,
  brake_type varchar NOT NULL,
  suspension_type varchar NOT NULL,
  foldable bool
);

-- Foreign Keys
ALTER TABLE vehicle ADD FOREIGN KEY (id_vehicle_type) REFERENCES vehicle_types (id_vehicle_type);
ALTER TABLE vehicle ADD FOREIGN KEY (id_vehicle_model) REFERENCES vehicle_models (id_vehicle_model);
ALTER TABLE vehicle ADD FOREIGN KEY (id_vehicle_alimentation_type) REFERENCES vehicle_alimentation_types (id_vehicle_alimentation_type);
ALTER TABLE vehicle ADD FOREIGN KEY (id_vehicle_brand) REFERENCES vehicle_brands (id_vehicle_brand);
ALTER TABLE vehicle_models ADD FOREIGN KEY (id_vehicle_brand) REFERENCES vehicle_brands (id_vehicle_brand);
ALTER TABLE cars ADD FOREIGN KEY (id_vehicle) REFERENCES vehicle (id_vehicle);
ALTER TABLE motorbikes ADD FOREIGN KEY (id_vehicle) REFERENCES vehicle (id_vehicle);
ALTER TABLE bikes ADD FOREIGN KEY (id_vehicle) REFERENCES vehicle (id_vehicle);

-- Dati di lookup
INSERT INTO vehicle_types (vehicle_type_name) VALUES
  ('Utilitaria'), ('SUV'), ('Berlina'), ('Sportiva'),
  ('Moto'), ('Scooter'), ('Furgone'), ('Pickup'), ('Minivan'), ('Camper');

INSERT INTO vehicle_alimentation_types (vehicle_alimentation_type_name) VALUES
  ('Benzina'), ('Diesel'), ('GPL'), ('Metano'), ('Elettrico'), ('Ibrida');

INSERT INTO vehicle_brands (vehicle_brand_name) VALUES
  ('Fiat'), ('Alfa Romeo'), ('Lancia'), ('Ferrari'), ('Lamborghini'),
  ('Maserati'), ('Audi'), ('BMW'), ('Mercedes-Benz'), ('Volkswagen'),
  ('Porsche'), ('Toyota'), ('Honda'), ('Nissan'), ('Ford'),
  ('Tesla'), ('Peugeot'), ('Renault'), ('Hyundai'), ('Kia');

INSERT INTO vehicle_models (vehicle_model_name, id_vehicle_brand) VALUES
  ('Panda', 1), ('500x', 1), ('Punto', 1), ('Bravo', 1),
  ('Giulia', 2), ('Stelvio', 2), ('Giulietta', 2),
  ('Ypsilon', 3),
  ('SF90 Stradale', 4),
  ('Huracán', 5), ('Aventador', 5), ('Urus', 5),
  ('Grecale', 6), ('Ghibli', 6),
  ('A4', 7), ('Q5', 7),
  ('Serie 3', 8),
  ('Classe A', 9),
  ('Golf', 10), ('Tiguan', 10),
  ('911 Carrera', 11), ('Cayenne', 11),
  ('Yaris', 12), ('Corolla', 12),
  ('Civic', 13), ('Jazz', 13),
  ('Mustang', 15), ('Fiesta', 15),
  ('Model 3', 16), ('Model S', 16), ('Model X', 16),
  ('208', 17),
  ('Clio', 18),
  ('Tucson', 19),
  ('Sportage', 20);
