-- =============================================
-- Setup completo vehicles_db
-- =============================================

-- Lookup semplici
CREATE TABLE vehicle_types (
  id_vehicle_type INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_type_name VARCHAR NOT NULL
);
CREATE TABLE vehicle_alimentation_types (
  id_vehicle_alimentation_type INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_alimentation_type_name VARCHAR NOT NULL
);
CREATE TABLE vehicle_brands (
  id_vehicle_brand INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_brand_name VARCHAR NOT NULL
);
CREATE TABLE vehicle_colors (
  id_color INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  color_name VARCHAR NOT NULL
);
CREATE TABLE brake_types (
  id_brake_type INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brake_type_name VARCHAR NOT NULL
);
CREATE TABLE suspension_types (
  id_suspension_type INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suspension_type_name VARCHAR NOT NULL
);
CREATE TABLE vehicle_models (
  id_vehicle_model INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_model_name VARCHAR NOT NULL,
  id_vehicle_brand INTEGER NOT NULL
);

-- Tabella principale (rinominata da vehicle)
CREATE TABLE vehicles (
  id_vehicle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle_type INTEGER NOT NULL,
  id_vehicle_model INTEGER NOT NULL,
  id_vehicle_alimentation_type INTEGER NOT NULL,
  id_vehicle_brand INTEGER NOT NULL,
  id_color INTEGER NOT NULL,
  number_of_wheels INTEGER NOT NULL,
  numbers_of_gears INTEGER NOT NULL,
  production_year DATE NOT NULL
);

-- Specializzazioni
CREATE TABLE cars (
  id_car INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle INTEGER NOT NULL,
  licence_plate VARCHAR NOT NULL,
  cc INTEGER,
  number_of_doors INTEGER NOT NULL,
  CONSTRAINT unique_car_plate UNIQUE (licence_plate)
);
CREATE TABLE motorbikes (
  id_motorbike INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle INTEGER NOT NULL,
  licence_plate VARCHAR NOT NULL,
  cc INTEGER,
  CONSTRAINT unique_moto_plate UNIQUE (licence_plate)
);
CREATE TABLE bikes (
  id_bike INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehicle INTEGER NOT NULL,
  id_brake_type INTEGER NOT NULL,
  id_suspension_type INTEGER NOT NULL,
  foldable BOOLEAN
);

-- Foreign Keys
ALTER TABLE vehicle_models   ADD FOREIGN KEY (id_vehicle_brand)              REFERENCES vehicle_brands (id_vehicle_brand);
ALTER TABLE vehicles         ADD FOREIGN KEY (id_vehicle_type)               REFERENCES vehicle_types (id_vehicle_type);
ALTER TABLE vehicles         ADD FOREIGN KEY (id_vehicle_model)              REFERENCES vehicle_models (id_vehicle_model);
ALTER TABLE vehicles         ADD FOREIGN KEY (id_vehicle_alimentation_type)  REFERENCES vehicle_alimentation_types (id_vehicle_alimentation_type);
ALTER TABLE vehicles         ADD FOREIGN KEY (id_vehicle_brand)              REFERENCES vehicle_brands (id_vehicle_brand);
ALTER TABLE vehicles         ADD FOREIGN KEY (id_color)                      REFERENCES vehicle_colors (id_color);
ALTER TABLE cars             ADD FOREIGN KEY (id_vehicle)                    REFERENCES vehicles (id_vehicle);
ALTER TABLE motorbikes       ADD FOREIGN KEY (id_vehicle)                    REFERENCES vehicles (id_vehicle);
ALTER TABLE bikes            ADD FOREIGN KEY (id_vehicle)                    REFERENCES vehicles (id_vehicle);
ALTER TABLE bikes            ADD FOREIGN KEY (id_brake_type)                 REFERENCES brake_types (id_brake_type);
ALTER TABLE bikes            ADD FOREIGN KEY (id_suspension_type)            REFERENCES suspension_types (id_suspension_type);

-- =============================================
-- Dati di lookup
-- =============================================

INSERT INTO vehicle_types (vehicle_type_name) VALUES
  ('Utilitaria'),('SUV'),('Berlina'),('Sportiva'),
  ('Moto'),('Scooter'),('Furgone'),('Pickup'),('Minivan'),('Camper'),
  ('Bici da Corsa'),('Mountain Bike'),('City Bike');

INSERT INTO vehicle_alimentation_types (vehicle_alimentation_type_name) VALUES
  ('Benzina'),('Diesel'),('GPL'),('Metano'),('Elettrico'),('Ibrida'),('Nessuna');

-- brand auto (1-20), moto (21-27), bici (28-30)
INSERT INTO vehicle_brands (vehicle_brand_name) VALUES
  ('Fiat'),('Alfa Romeo'),('Lancia'),('Ferrari'),('Lamborghini'),
  ('Maserati'),('Audi'),('BMW'),('Mercedes-Benz'),('Volkswagen'),
  ('Porsche'),('Toyota'),('Honda'),('Nissan'),('Ford'),
  ('Tesla'),('Peugeot'),('Renault'),('Hyundai'),('Kia'),
  ('Ducati'),('Kawasaki'),('Yamaha'),('Triumph'),('KTM'),
  ('Harley-Davidson'),('Aprilia'),
  ('Trek'),('Giant'),('Bianchi');

INSERT INTO vehicle_colors (color_name) VALUES
  ('Rosso'),('Nero'),('Bianco'),('Grigio'),('Blu'),
  ('Verde'),('Giallo'),('Arancione'),('Celeste'),('Argento'),
  ('Bordeaux'),('Marrone');

INSERT INTO brake_types (brake_type_name) VALUES
  ('V-Brake'),('Disco Meccanico'),('Disco Idraulico'),('Cantilever'),('Coaster');

INSERT INTO suspension_types (suspension_type_name) VALUES
  ('Rigida'),('Anteriore'),('Full'),('Elettronica');

-- modelli auto (1-35), moto (36-46), bici (47-52)
INSERT INTO vehicle_models (vehicle_model_name, id_vehicle_brand) VALUES
  ('Panda',1),('500x',1),('Punto',1),('Bravo',1),
  ('Giulia',2),('Stelvio',2),('Giulietta',2),
  ('Ypsilon',3),
  ('SF90 Stradale',4),
  ('Huracan',5),('Aventador',5),('Urus',5),
  ('Grecale',6),('Ghibli',6),
  ('A4',7),('Q5',7),
  ('Serie 3',8),
  ('Classe A',9),
  ('Golf',10),('Tiguan',10),
  ('911 Carrera',11),('Cayenne',11),
  ('Yaris',12),('Corolla',12),
  ('Civic',13),('Jazz',13),
  ('Mustang',15),('Fiesta',15),
  ('Model 3',16),('Model S',16),('Model X',16),
  ('208',17),('Clio',18),('Tucson',19),('Sportage',20),
  ('Panigale V4',21),
  ('Ninja ZX-10R',22),
  ('YZF-R1',23),('MT-09',23),
  ('Speed Triple',24),('Tiger 900',24),
  ('Duke 390',25),('Adventure 1290',25),
  ('Fat Boy',26),
  ('RSV4',27),
  ('CBR600RR',13),('Africa Twin',13),
  ('Emonda SLR',28),('Domane AL',28),
  ('TCR Advanced',29),('Trance X',29),
  ('Oltre RC',30),('Infinito CV',30);

-- =============================================
-- I veicoli NON vengono inseriti qui.
-- Vengono caricati all'avvio del programma
-- dai file in data-files/
--   cars_default.txt
--   motorbikes_default.txt
--   bikes_default.txt
-- =============================================
